-- Generated by `pnpm db:gen-types`. Do not edit.
--
-- PostgreSQL database dump
--


-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
-- SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";

--
-- Name: SCHEMA "public"; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA "public" IS 'standard public schema';


--
-- Name: analysis_attempt_status; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE "public"."analysis_attempt_status" AS ENUM (
    'pending',
    'processing',
    'succeeded',
    'failed',
    'canceled'
);


ALTER TYPE "public"."analysis_attempt_status" OWNER TO "postgres";

--
-- Name: analysis_failure_reason; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE "public"."analysis_failure_reason" AS ENUM (
    'child_crashed',
    'hung',
    'hard_timeout',
    'infrastructure',
    'contract_violation',
    'upstream_api',
    'abandoned',
    'unknown',
    'shut_down',
    'unusable_data'
);


ALTER TYPE "public"."analysis_failure_reason" OWNER TO "postgres";

--
-- Name: audit_actor_kind; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE "public"."audit_actor_kind" AS ENUM (
    'user',
    'superadmin',
    'system',
    'gbd_manual'
);


ALTER TYPE "public"."audit_actor_kind" OWNER TO "postgres";

--
-- Name: counts_basis; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE "public"."counts_basis" AS ENUM (
    'people',
    'meals'
);


ALTER TYPE "public"."counts_basis" OWNER TO "postgres";

--
-- Name: organization_invite_status; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE "public"."organization_invite_status" AS ENUM (
    'pending',
    'accepted',
    'declined',
    'revoked',
    'expired',
    'superseded'
);


ALTER TYPE "public"."organization_invite_status" OWNER TO "postgres";

--
-- Name: organization_role; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE "public"."organization_role" AS ENUM (
    'member',
    'admin'
);


ALTER TYPE "public"."organization_role" OWNER TO "postgres";

--
-- Name: rejected_upload_reason; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE "public"."rejected_upload_reason" AS ENUM (
    'invalid_metadata',
    'too_large',
    'bad_columns',
    'unparseable',
    'empty',
    'bad_rows',
    'other',
    'rate_limited'
);


ALTER TYPE "public"."rejected_upload_reason" OWNER TO "postgres";

--
-- Name: result_file_kind; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE "public"."result_file_kind" AS ENUM (
    'pdf',
    'xlsx'
);


ALTER TYPE "public"."result_file_kind" OWNER TO "postgres";

--
-- Name: unit_system; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE "public"."unit_system" AS ENUM (
    'lb',
    'kg'
);


ALTER TYPE "public"."unit_system" OWNER TO "postgres";

--
-- Name: analysis_attempt_check_has_result_files(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE OR REPLACE FUNCTION "public"."analysis_attempt_check_has_result_files"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
    DECLARE
      current_status analysis_attempt_status;
    BEGIN
      SELECT status INTO current_status FROM analysis_attempt WHERE id = NEW.id;

      -- Deleted in the same transaction it was created in: nothing to enforce.
      IF NOT FOUND OR current_status <> 'succeeded' THEN
        RETURN NULL;
      END IF;

      IF NOT EXISTS (
        SELECT 1 FROM result_file WHERE analysis_attempt_id = NEW.id AND kind = 'pdf'
      ) THEN
        RAISE EXCEPTION 'analysis_attempt % succeeded with no pdf result file', NEW.id
          USING ERRCODE = 'check_violation',
                CONSTRAINT = 'analysis_attempt_succeeded_has_pdf',
                TABLE = 'analysis_attempt';
      END IF;

      IF NOT EXISTS (
        SELECT 1 FROM result_file WHERE analysis_attempt_id = NEW.id AND kind = 'xlsx'
      ) THEN
        RAISE EXCEPTION 'analysis_attempt % succeeded with no xlsx result file', NEW.id
          USING ERRCODE = 'check_violation',
                CONSTRAINT = 'analysis_attempt_succeeded_has_xlsx',
                TABLE = 'analysis_attempt';
      END IF;

      RETURN NULL;
    END;
    $$;


ALTER FUNCTION "public"."analysis_attempt_check_has_result_files"() OWNER TO "postgres";

--
-- Name: analysis_attempt_check_new_attempt(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE OR REPLACE FUNCTION "public"."analysis_attempt_check_new_attempt"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
    DECLARE
      report_deleted_at timestamptz;
      latest_number smallint;
      latest_status analysis_attempt_status;
    BEGIN
      -- Lock the report row FOR NO KEY UPDATE rather than a plain read: the insert's own
      -- foreign key only takes KEY SHARE, which wouldn't conflict with a concurrent delete's
      -- UPDATE of deleted_at, so a retry and a delete could otherwise both commit. Locking here
      -- also fixes the lock order for anything writing both tables — report, then
      -- analysis_attempt.
      SELECT deleted_at INTO report_deleted_at
        FROM report
       WHERE id = NEW.report_id
         FOR NO KEY UPDATE;

      IF report_deleted_at IS NOT NULL THEN
        RAISE EXCEPTION 'report %: deleted at %, so a new attempt is not allowed',
          NEW.report_id, report_deleted_at
          USING ERRCODE = 'check_violation',
                CONSTRAINT = 'analysis_attempt_no_attempt_for_deleted_report',
                TABLE = 'analysis_attempt';
      END IF;

      -- BEFORE INSERT, so NEW is not in the table yet and "latest" needs no self-exclusion.
      SELECT attempt_number, status INTO latest_number, latest_status
        FROM analysis_attempt
       WHERE report_id = NEW.report_id
       ORDER BY attempt_number DESC
       LIMIT 1;

      IF NOT FOUND THEN
        IF NEW.attempt_number <> 1 THEN
          RAISE EXCEPTION 'report %: the first attempt must be number 1, not %',
            NEW.report_id, NEW.attempt_number
            USING ERRCODE = 'check_violation',
                  CONSTRAINT = 'analysis_attempt_new_attempt_only_after_failure',
                  TABLE = 'analysis_attempt';
        END IF;
        RETURN NEW;
      END IF;

      -- Retrying is user-initiated and only after a failure. A canceled or succeeded attempt is
      -- the end of the line for that report. See ARCHITECTURE.md § Worker queue.
      IF latest_status <> 'failed' THEN
        RAISE EXCEPTION 'report %: attempt % is %, so a new attempt is not allowed',
          NEW.report_id, latest_number, latest_status
          USING ERRCODE = 'check_violation',
                CONSTRAINT = 'analysis_attempt_new_attempt_only_after_failure',
                TABLE = 'analysis_attempt';
      END IF;

      IF NEW.attempt_number <> latest_number + 1 THEN
        RAISE EXCEPTION 'report %: the next attempt must be number %, not %',
          NEW.report_id, latest_number + 1, NEW.attempt_number
          USING ERRCODE = 'check_violation',
                CONSTRAINT = 'analysis_attempt_new_attempt_only_after_failure',
                TABLE = 'analysis_attempt';
      END IF;

      RETURN NEW;
    END;
    $$;


ALTER FUNCTION "public"."analysis_attempt_check_new_attempt"() OWNER TO "postgres";

--
-- Name: analysis_attempt_check_terminal_is_final(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE OR REPLACE FUNCTION "public"."analysis_attempt_check_terminal_is_final"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
    BEGIN
      -- Compared row-wise with the mutable columns masked out, rather than as a list of
      -- OLD.x = NEW.x tests, so that a column added later is frozen by default instead of
      -- silently becoming mutable after an attempt has finished.
      IF to_jsonb(OLD) - ARRAY['notification_email_sent_at',
                               'notification_claimed_at',
                               'notification_claimed_by_worker_id',
                               'notification_attempts']
         = to_jsonb(NEW) - ARRAY['notification_email_sent_at',
                                 'notification_claimed_at',
                                 'notification_claimed_by_worker_id',
                                 'notification_attempts'] THEN
        RETURN NEW;
      END IF;

      RAISE EXCEPTION
        'analysis_attempt %: % is terminal, so only the notification columns may change',
        OLD.id, OLD.status
        USING ERRCODE = 'check_violation',
              CONSTRAINT = 'analysis_attempt_terminal_is_final',
              TABLE = 'analysis_attempt';
    END;
    $$;


ALTER FUNCTION "public"."analysis_attempt_check_terminal_is_final"() OWNER TO "postgres";

--
-- Name: audit_event_reject_mutation(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE OR REPLACE FUNCTION "public"."audit_event_reject_mutation"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
    BEGIN
      RAISE EXCEPTION 'audit_event is append-only; % is not permitted', TG_OP
        USING ERRCODE = 'check_violation',
              CONSTRAINT = 'audit_event_is_append_only',
              TABLE = 'audit_event';
    END;
    $$;


ALTER FUNCTION "public"."audit_event_reject_mutation"() OWNER TO "postgres";

--
-- Name: handle_new_auth_user(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE OR REPLACE FUNCTION "public"."handle_new_auth_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
    BEGIN
      INSERT INTO public.app_user (id)
      VALUES (NEW.id)
      ON CONFLICT (id) DO NOTHING;
      RETURN NULL;
    END;
    $$;


ALTER FUNCTION "public"."handle_new_auth_user"() OWNER TO "postgres";

--
-- Name: organization_check_has_member(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE OR REPLACE FUNCTION "public"."organization_check_has_member"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
    BEGIN
      -- Created and dropped in the same transaction: nothing to enforce.
      IF NOT EXISTS (SELECT 1 FROM organization WHERE id = NEW.id) THEN
        RETURN NULL;
      END IF;

      IF EXISTS (SELECT 1 FROM organization_member WHERE organization_id = NEW.id) THEN
        RETURN NULL;
      END IF;

      RAISE EXCEPTION 'organization % must be created with at least one member', NEW.id
        USING ERRCODE = 'check_violation',
              CONSTRAINT = 'organization_has_a_member',
              TABLE = 'organization';
    END;
    $$;


ALTER FUNCTION "public"."organization_check_has_member"() OWNER TO "postgres";

--
-- Name: organization_count_against_creator(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE OR REPLACE FUNCTION "public"."organization_count_against_creator"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
    BEGIN
      UPDATE app_user
         SET organizations_created_count = organizations_created_count + 1
       WHERE id = NEW.created_by_user_id;
      RETURN NULL;
    END;
    $$;


ALTER FUNCTION "public"."organization_count_against_creator"() OWNER TO "postgres";

--
-- Name: organization_member_check_admin_remains(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE OR REPLACE FUNCTION "public"."organization_member_check_admin_remains"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
    DECLARE
      affected_organization_id uuid := coalesce(OLD.organization_id, NEW.organization_id);
    BEGIN
      -- One statement doing two jobs.
      --
      -- The lock serializes membership changes per organization. Deferring to commit is not a
      -- serializable guarantee on its own: without this, two transactions can each still see the
      -- other's committed admin, both pass, and both commit, leaving zero. FOR NO KEY UPDATE is
      -- the right strength — it conflicts with itself, but not with the FOR KEY SHARE locks our
      -- own foreign keys take. This relies on READ COMMITTED, where the count below re-reads
      -- under a fresh snapshot once the lock is granted.
      --
      -- And FOUND answers "is the organization gone?". Deleting an organization cascades to its
      -- members and queues this trigger; because it is deferred, by the time it runs the
      -- organization row is already absent, and that absence is exactly what distinguishes a
      -- deleted organization from one that just lost its last admin.
      PERFORM 1 FROM organization WHERE id = affected_organization_id FOR NO KEY UPDATE;
      IF NOT FOUND THEN
        RETURN NULL;
      END IF;

      -- app_user.is_superadmin is deliberately not consulted: a superadmin is admin everywhere
      -- but fills no organization's admin seat.
      IF EXISTS (
        SELECT 1 FROM organization_member
        WHERE organization_id = affected_organization_id AND role = 'admin'
      ) THEN
        RETURN NULL;
      END IF;

      RAISE EXCEPTION 'organization % must keep at least one admin', affected_organization_id
        USING ERRCODE = 'check_violation',
              CONSTRAINT = 'organization_member_at_least_one_admin',
              TABLE = 'organization_member';
    END;
    $$;


ALTER FUNCTION "public"."organization_member_check_admin_remains"() OWNER TO "postgres";

--
-- Name: report_check_has_input_file(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE OR REPLACE FUNCTION "public"."report_check_has_input_file"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
    BEGIN
      -- Deleted in the same transaction it was created in: nothing to enforce.
      IF NOT EXISTS (SELECT 1 FROM report WHERE id = NEW.id) THEN
        RETURN NULL;
      END IF;

      IF EXISTS (SELECT 1 FROM input_file WHERE report_id = NEW.id) THEN
        RETURN NULL;
      END IF;

      RAISE EXCEPTION 'report % must have an input file', NEW.id
        USING ERRCODE = 'check_violation',
              CONSTRAINT = 'report_has_an_input_file',
              TABLE = 'report';
    END;
    $$;


ALTER FUNCTION "public"."report_check_has_input_file"() OWNER TO "postgres";

--
-- Name: set_updated_at(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE OR REPLACE FUNCTION "public"."set_updated_at"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
    BEGIN
      NEW.updated_at := now();
      RETURN NEW;
    END;
    $$;


ALTER FUNCTION "public"."set_updated_at"() OWNER TO "postgres";

--
-- Name: uuidv7(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE OR REPLACE FUNCTION "public"."uuidv7"() RETURNS "uuid"
    LANGUAGE "sql" PARALLEL SAFE
    AS $$
      SELECT encode(
        set_bit(
          set_bit(
            overlay(
              uuid_send(gen_random_uuid())
              PLACING substring(
                int8send(floor(extract(epoch FROM clock_timestamp()) * 1000)::bigint)
                FROM 3
              )
              FROM 1 FOR 6
            ),
            52, 1
          ),
          53, 1
        ),
        'hex'
      )::uuid
    $$;


ALTER FUNCTION "public"."uuidv7"() OWNER TO "postgres";

--
-- Name: FUNCTION "uuidv7"(); Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON FUNCTION "public"."uuidv7"() IS 'Time-ordered UUID v7. Replace with the built-in on Postgres 18.';


SET default_tablespace = '';

SET default_table_access_method = "heap";

--
-- Name: analysis_attempt; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE IF NOT EXISTS "public"."analysis_attempt" (
    "id" "uuid" DEFAULT "public"."uuidv7"() NOT NULL,
    "report_id" "uuid" NOT NULL,
    "attempt_number" smallint NOT NULL,
    "status" "public"."analysis_attempt_status" NOT NULL,
    "requested_by_user_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "worker_id" "text",
    "claimed_at" timestamp with time zone,
    "lease_renewed_at" timestamp with time zone,
    "finished_at" timestamp with time zone,
    "cancel_requested_at" timestamp with time zone,
    "failure_reason" "public"."analysis_failure_reason",
    "failure_detail" "text",
    "reaped_by_worker_id" "text",
    "notification_email_sent_at" timestamp with time zone,
    "notification_claimed_at" timestamp with time zone,
    "notification_claimed_by_worker_id" "text",
    "notification_attempts" integer DEFAULT 0 NOT NULL,
    "required_contract_version" smallint DEFAULT 1 NOT NULL,
    CONSTRAINT "analysis_attempt_attempt_number_range" CHECK ((("attempt_number" >= 1) AND ("attempt_number" <= 5))),
    CONSTRAINT "analysis_attempt_cancel_requested_at_after_created_at" CHECK ((("cancel_requested_at" IS NULL) OR ("cancel_requested_at" >= "created_at"))),
    CONSTRAINT "analysis_attempt_canceled_is_not_notified" CHECK ((("notification_claimed_at" IS NULL) OR ("status" <> 'canceled'::"public"."analysis_attempt_status"))),
    CONSTRAINT "analysis_attempt_canceled_requires_request" CHECK ((("status" <> 'canceled'::"public"."analysis_attempt_status") OR ("cancel_requested_at" IS NOT NULL))),
    CONSTRAINT "analysis_attempt_claimed_at_after_created_at" CHECK ((("claimed_at" IS NULL) OR ("claimed_at" >= "created_at"))),
    CONSTRAINT "analysis_attempt_failure_reason_iff_failed" CHECK ((("status" = 'failed'::"public"."analysis_attempt_status") = ("failure_reason" IS NOT NULL))),
    CONSTRAINT "analysis_attempt_finished_at_after_created_at" CHECK ((("finished_at" IS NULL) OR ("finished_at" >= "created_at"))),
    CONSTRAINT "analysis_attempt_finished_at_after_lease_renewed" CHECK ((("finished_at" IS NULL) OR ("lease_renewed_at" IS NULL) OR ("finished_at" >= "lease_renewed_at"))),
    CONSTRAINT "analysis_attempt_finished_at_iff_terminal" CHECK ((("status" = ANY (ARRAY['succeeded'::"public"."analysis_attempt_status", 'failed'::"public"."analysis_attempt_status", 'canceled'::"public"."analysis_attempt_status"])) = ("finished_at" IS NOT NULL))),
    CONSTRAINT "analysis_attempt_lease_renewed_after_claimed_at" CHECK ((("lease_renewed_at" IS NULL) OR ("claimed_at" IS NULL) OR ("lease_renewed_at" >= "claimed_at"))),
    CONSTRAINT "analysis_attempt_lease_renewed_after_created_at" CHECK ((("lease_renewed_at" IS NULL) OR ("lease_renewed_at" >= "created_at"))),
    CONSTRAINT "analysis_attempt_notification_attempts_iff_claimed" CHECK ((("notification_attempts" > 0) = ("notification_claimed_at" IS NOT NULL))),
    CONSTRAINT "analysis_attempt_notification_attempts_non_negative" CHECK (("notification_attempts" >= 0)),
    CONSTRAINT "analysis_attempt_notification_claim_requires_finished" CHECK ((("notification_claimed_at" IS NULL) OR ("finished_at" IS NOT NULL))),
    CONSTRAINT "analysis_attempt_notification_claimed_by_iff_claimed" CHECK ((("notification_claimed_at" IS NOT NULL) = ("notification_claimed_by_worker_id" IS NOT NULL))),
    CONSTRAINT "analysis_attempt_notification_requires_finished" CHECK ((("notification_email_sent_at" IS NULL) OR ("finished_at" IS NOT NULL))),
    CONSTRAINT "analysis_attempt_notification_sent_requires_claim" CHECK ((("notification_email_sent_at" IS NULL) OR ("notification_claimed_at" IS NOT NULL))),
    CONSTRAINT "analysis_attempt_pending_is_unclaimed" CHECK ((("status" <> 'pending'::"public"."analysis_attempt_status") OR (("worker_id" IS NULL) AND ("claimed_at" IS NULL) AND ("lease_renewed_at" IS NULL)))),
    CONSTRAINT "analysis_attempt_processing_is_claimed" CHECK ((("status" <> 'processing'::"public"."analysis_attempt_status") OR (("worker_id" IS NOT NULL) AND ("claimed_at" IS NOT NULL) AND ("lease_renewed_at" IS NOT NULL) AND ("finished_at" IS NULL)))),
    CONSTRAINT "analysis_attempt_required_contract_version_positive" CHECK (("required_contract_version" >= 1))
);


ALTER TABLE "public"."analysis_attempt" OWNER TO "postgres";

--
-- Name: TABLE "analysis_attempt"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE "public"."analysis_attempt" IS 'The queue and state machine between the web app and the workers. Checks cannot be deferred, so a transition to a terminal status must set status, finished_at and failure_reason in one UPDATE.';


--
-- Name: COLUMN "analysis_attempt"."worker_id"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN "public"."analysis_attempt"."worker_id" IS 'The supervising worker''s identity, unique per process — not per host. A restarted container must
       not reuse its predecessor''s id, or the ownership guard on every terminal write stops
       distinguishing this supervisor from a dead one.';


--
-- Name: COLUMN "analysis_attempt"."lease_renewed_at"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN "public"."analysis_attempt"."lease_renewed_at" IS 'When a worker last confirmed it was still supervising this attempt and would still reach a verdict for it.';


--
-- Name: COLUMN "analysis_attempt"."notification_claimed_at"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN "public"."analysis_attempt"."notification_claimed_at" IS 'Set by a worker before it sends the notification email, so a second worker cannot claim the
       same row. Left in place if the send fails, so the row stays claimed until it expires — that
       expiry is what lets a later sweep retry the send instead of the claim silently losing it.';


--
-- Name: COLUMN "analysis_attempt"."notification_claimed_by_worker_id"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN "public"."analysis_attempt"."notification_claimed_by_worker_id" IS 'Debugging only, symmetric with reaped_by_worker_id.';


--
-- Name: COLUMN "analysis_attempt"."notification_attempts"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN "public"."analysis_attempt"."notification_attempts" IS 'Incremented by the claim, before the send is attempted. Bounds retries: once it reaches the
       configured maximum the row stops being claimed, however stale its claim, so a permanently
       undeliverable address costs a fixed number of provider requests rather than an unbounded
       retry loop.';


--
-- Name: COLUMN "analysis_attempt"."required_contract_version"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN "public"."analysis_attempt"."required_contract_version" IS 'The lowest worker contract version that can safely claim this row, so an old worker leaves
       an attempt it cannot handle in the queue instead of claiming and failing it.';


--
-- Name: app_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE IF NOT EXISTS "public"."app_user" (
    "id" "uuid" NOT NULL,
    "display_name" "text",
    "is_superadmin" boolean DEFAULT false NOT NULL,
    "organizations_created_count" integer DEFAULT 0 NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "app_user_organizations_created_count_max" CHECK (("organizations_created_count" <= 5)),
    CONSTRAINT "app_user_organizations_created_count_non_negative" CHECK (("organizations_created_count" >= 0))
);


ALTER TABLE "public"."app_user" OWNER TO "postgres";

--
-- Name: TABLE "app_user"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE "public"."app_user" IS 'Mirrors auth.users, which owns email and created_at. Rows are created by a trigger on auth.users.';


--
-- Name: audit_event; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE IF NOT EXISTS "public"."audit_event" (
    "id" bigint NOT NULL,
    "occurred_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "action" "text" NOT NULL,
    "actor_user_id" "uuid",
    "actor_kind" "public"."audit_actor_kind" NOT NULL,
    "organization_id" "uuid",
    "target_type" "text",
    "target_id" "uuid",
    "detail" "jsonb"
);


ALTER TABLE "public"."audit_event" OWNER TO "postgres";

--
-- Name: TABLE "audit_event"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE "public"."audit_event" IS 'Append-only trail. Deliberately has no foreign keys: users and organizations can be hard-deleted, and their IDs must survive here. Not user-visible.';


--
-- Name: audit_event_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE "public"."audit_event" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "public"."audit_event_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: input_file; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE IF NOT EXISTS "public"."input_file" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "report_id" "uuid" NOT NULL,
    "storage_key" "text" NOT NULL,
    "byte_size" integer NOT NULL,
    "content_type" "text" NOT NULL,
    "original_filename" "text" NOT NULL,
    "checksum_sha256" "bytea" NOT NULL,
    "is_modified" boolean NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "input_file_byte_size_positive" CHECK (("byte_size" > 0)),
    CONSTRAINT "input_file_checksum_sha256_length" CHECK (("octet_length"("checksum_sha256") = 32))
);


ALTER TABLE "public"."input_file" OWNER TO "postgres";

--
-- Name: COLUMN "input_file"."is_modified"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN "public"."input_file"."is_modified" IS 'Whether storage_key holds bytes the user did not send. When true, the upload as received is at the same key suffixed -original, which no row references. When false, storage_key is it.';


--
-- Name: kysely_migration; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE IF NOT EXISTS "public"."kysely_migration" (
    "name" character varying(255) NOT NULL,
    "timestamp" character varying(255) NOT NULL
);


ALTER TABLE "public"."kysely_migration" OWNER TO "postgres";

--
-- Name: kysely_migration_lock; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE IF NOT EXISTS "public"."kysely_migration_lock" (
    "id" character varying(255) NOT NULL,
    "is_locked" integer DEFAULT 0 NOT NULL
);


ALTER TABLE "public"."kysely_migration_lock" OWNER TO "postgres";

--
-- Name: organization; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE IF NOT EXISTS "public"."organization" (
    "id" "uuid" DEFAULT "public"."uuidv7"() NOT NULL,
    "name" "text" NOT NULL,
    "created_by_user_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."organization" OWNER TO "postgres";

--
-- Name: organization_invite; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE IF NOT EXISTS "public"."organization_invite" (
    "id" "uuid" DEFAULT "public"."uuidv7"() NOT NULL,
    "organization_id" "uuid" NOT NULL,
    "email" "text" NOT NULL,
    "role" "public"."organization_role" NOT NULL,
    "invited_by_user_id" "uuid",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "expires_at" timestamp with time zone NOT NULL,
    "status" "public"."organization_invite_status" NOT NULL,
    CONSTRAINT "organization_invite_email_is_lowercase" CHECK (("email" = "lower"("email"))),
    CONSTRAINT "organization_invite_expires_at_after_created_at" CHECK (("expires_at" > "created_at"))
);


ALTER TABLE "public"."organization_invite" OWNER TO "postgres";

--
-- Name: organization_member; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE IF NOT EXISTS "public"."organization_member" (
    "user_id" "uuid" NOT NULL,
    "organization_id" "uuid" NOT NULL,
    "role" "public"."organization_role" NOT NULL,
    "joined_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."organization_member" OWNER TO "postgres";

--
-- Name: rejected_upload; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE IF NOT EXISTS "public"."rejected_upload" (
    "id" "uuid" DEFAULT "public"."uuidv7"() NOT NULL,
    "organization_id" "uuid" NOT NULL,
    "created_by_user_id" "uuid",
    "report_name" "text",
    "report_site_name" "text",
    "report_counts_basis" "text",
    "report_monthly_counts" "text",
    "report_unit_system" "text",
    "input_file_storage_key" "text",
    "input_file_byte_size" integer,
    "input_file_original_filename" "text",
    "rejection_reason" "public"."rejected_upload_reason" NOT NULL,
    "rejection_detail" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."rejected_upload" OWNER TO "postgres";

--
-- Name: TABLE "rejected_upload"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE "public"."rejected_upload" IS 'An upload that failed validation and never became a report.';


--
-- Name: report; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE IF NOT EXISTS "public"."report" (
    "id" "uuid" DEFAULT "public"."uuidv7"() NOT NULL,
    "organization_id" "uuid" NOT NULL,
    "created_by_user_id" "uuid",
    "name" "text" NOT NULL,
    "site_name" "text",
    "counts_basis" "public"."counts_basis" NOT NULL,
    "monthly_counts" "jsonb" NOT NULL,
    "unit_system" "public"."unit_system" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "deleted_at" timestamp with time zone,
    CONSTRAINT "report_deleted_at_after_created_at" CHECK ((("deleted_at" IS NULL) OR ("deleted_at" >= "created_at"))),
    CONSTRAINT "report_monthly_counts_is_object" CHECK ((("jsonb_typeof"("monthly_counts") = 'object'::"text") AND ("monthly_counts" <> '{}'::"jsonb")))
);


ALTER TABLE "public"."report" OWNER TO "postgres";

--
-- Name: COLUMN "report"."monthly_counts"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN "public"."report"."monthly_counts" IS 'Month to diner or meal count, keyed YYYY-MM. Which of the two is counts_basis.';


--
-- Name: result_file; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE IF NOT EXISTS "public"."result_file" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "analysis_attempt_id" "uuid" NOT NULL,
    "kind" "public"."result_file_kind" NOT NULL,
    "storage_key" "text" NOT NULL,
    "byte_size" integer NOT NULL,
    "content_type" "text" NOT NULL,
    "checksum_sha256" "bytea" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    CONSTRAINT "result_file_byte_size_positive" CHECK (("byte_size" > 0)),
    CONSTRAINT "result_file_checksum_sha256_length" CHECK (("octet_length"("checksum_sha256") = 32))
);


ALTER TABLE "public"."result_file" OWNER TO "postgres";

--
-- Name: analysis_attempt analysis_attempt_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."analysis_attempt"
    ADD CONSTRAINT "analysis_attempt_pkey" PRIMARY KEY ("id");


--
-- Name: analysis_attempt analysis_attempt_report_id_attempt_number; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."analysis_attempt"
    ADD CONSTRAINT "analysis_attempt_report_id_attempt_number" UNIQUE ("report_id", "attempt_number");


--
-- Name: app_user app_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."app_user"
    ADD CONSTRAINT "app_user_pkey" PRIMARY KEY ("id");


--
-- Name: audit_event audit_event_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."audit_event"
    ADD CONSTRAINT "audit_event_pkey" PRIMARY KEY ("id");


--
-- Name: input_file input_file_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."input_file"
    ADD CONSTRAINT "input_file_pkey" PRIMARY KEY ("id");


--
-- Name: input_file input_file_report_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."input_file"
    ADD CONSTRAINT "input_file_report_id_key" UNIQUE ("report_id");


--
-- Name: input_file input_file_storage_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."input_file"
    ADD CONSTRAINT "input_file_storage_key_key" UNIQUE ("storage_key");


--
-- Name: kysely_migration_lock kysely_migration_lock_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."kysely_migration_lock"
    ADD CONSTRAINT "kysely_migration_lock_pkey" PRIMARY KEY ("id");


--
-- Name: kysely_migration kysely_migration_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."kysely_migration"
    ADD CONSTRAINT "kysely_migration_pkey" PRIMARY KEY ("name");


--
-- Name: organization_invite organization_invite_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."organization_invite"
    ADD CONSTRAINT "organization_invite_pkey" PRIMARY KEY ("id");


--
-- Name: organization_member organization_member_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."organization_member"
    ADD CONSTRAINT "organization_member_pkey" PRIMARY KEY ("user_id", "organization_id");


--
-- Name: organization organization_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."organization"
    ADD CONSTRAINT "organization_pkey" PRIMARY KEY ("id");


--
-- Name: rejected_upload rejected_upload_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."rejected_upload"
    ADD CONSTRAINT "rejected_upload_pkey" PRIMARY KEY ("id");


--
-- Name: report report_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."report"
    ADD CONSTRAINT "report_pkey" PRIMARY KEY ("id");


--
-- Name: result_file result_file_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."result_file"
    ADD CONSTRAINT "result_file_pkey" PRIMARY KEY ("id");


--
-- Name: result_file result_file_storage_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."result_file"
    ADD CONSTRAINT "result_file_storage_key_key" UNIQUE ("storage_key");


--
-- Name: analysis_attempt_notification_pending; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "analysis_attempt_notification_pending" ON "public"."analysis_attempt" USING "btree" ("finished_at") WHERE (("notification_email_sent_at" IS NULL) AND ("finished_at" IS NOT NULL) AND ("status" <> 'canceled'::"public"."analysis_attempt_status") AND ("notification_attempts" < 5));


--
-- Name: analysis_attempt_one_active_per_report; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "analysis_attempt_one_active_per_report" ON "public"."analysis_attempt" USING "btree" ("report_id") WHERE ("status" = ANY (ARRAY['pending'::"public"."analysis_attempt_status", 'processing'::"public"."analysis_attempt_status"]));


--
-- Name: analysis_attempt_pending_queue; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "analysis_attempt_pending_queue" ON "public"."analysis_attempt" USING "btree" ("created_at") WHERE ("status" = 'pending'::"public"."analysis_attempt_status");


--
-- Name: analysis_attempt_processing_lease_renewed_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "analysis_attempt_processing_lease_renewed_at" ON "public"."analysis_attempt" USING "btree" ("lease_renewed_at") WHERE ("status" = 'processing'::"public"."analysis_attempt_status");


--
-- Name: analysis_attempt_requested_by_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "analysis_attempt_requested_by_user_id" ON "public"."analysis_attempt" USING "btree" ("requested_by_user_id");


--
-- Name: audit_event_organization_id_occurred_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "audit_event_organization_id_occurred_at" ON "public"."audit_event" USING "btree" ("organization_id", "occurred_at" DESC);


--
-- Name: organization_created_by_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "organization_created_by_user_id" ON "public"."organization" USING "btree" ("created_by_user_id");


--
-- Name: organization_invite_invited_by_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "organization_invite_invited_by_user_id" ON "public"."organization_invite" USING "btree" ("invited_by_user_id");


--
-- Name: organization_invite_one_pending_per_email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "organization_invite_one_pending_per_email" ON "public"."organization_invite" USING "btree" ("organization_id", "email") WHERE ("status" = 'pending'::"public"."organization_invite_status");


--
-- Name: organization_invite_organization_id_created_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "organization_invite_organization_id_created_at" ON "public"."organization_invite" USING "btree" ("organization_id", "created_at" DESC);


--
-- Name: organization_invite_pending_by_email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "organization_invite_pending_by_email" ON "public"."organization_invite" USING "btree" ("email") WHERE ("status" = 'pending'::"public"."organization_invite_status");


--
-- Name: organization_member_organization_id_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "organization_member_organization_id_user_id" ON "public"."organization_member" USING "btree" ("organization_id", "user_id");


--
-- Name: organization_name_unique_ci; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "organization_name_unique_ci" ON "public"."organization" USING "btree" ("lower"("name"));


--
-- Name: rejected_upload_created_by_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "rejected_upload_created_by_user_id" ON "public"."rejected_upload" USING "btree" ("created_by_user_id");


--
-- Name: rejected_upload_organization_id_created_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "rejected_upload_organization_id_created_at" ON "public"."rejected_upload" USING "btree" ("organization_id", "created_at" DESC);


--
-- Name: report_created_by_user_id_created_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "report_created_by_user_id_created_at" ON "public"."report" USING "btree" ("created_by_user_id", "created_at" DESC);


--
-- Name: report_organization_id_created_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "report_organization_id_created_at" ON "public"."report" USING "btree" ("organization_id", "created_at" DESC);


--
-- Name: result_file_analysis_attempt_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "result_file_analysis_attempt_id" ON "public"."result_file" USING "btree" ("analysis_attempt_id");


--
-- Name: result_file_one_pdf_per_attempt; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "result_file_one_pdf_per_attempt" ON "public"."result_file" USING "btree" ("analysis_attempt_id") WHERE ("kind" = 'pdf'::"public"."result_file_kind");


--
-- Name: result_file_one_xlsx_per_attempt; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "result_file_one_xlsx_per_attempt" ON "public"."result_file" USING "btree" ("analysis_attempt_id") WHERE ("kind" = 'xlsx'::"public"."result_file_kind");


--
-- Name: analysis_attempt analysis_attempt_new_attempt_only_after_failure; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE OR REPLACE TRIGGER "analysis_attempt_new_attempt_only_after_failure" BEFORE INSERT ON "public"."analysis_attempt" FOR EACH ROW EXECUTE FUNCTION "public"."analysis_attempt_check_new_attempt"();


--
-- Name: analysis_attempt analysis_attempt_succeeded_has_result_files; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE CONSTRAINT TRIGGER "analysis_attempt_succeeded_has_result_files" AFTER INSERT OR UPDATE ON "public"."analysis_attempt" DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION "public"."analysis_attempt_check_has_result_files"();


--
-- Name: analysis_attempt analysis_attempt_terminal_is_final; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE OR REPLACE TRIGGER "analysis_attempt_terminal_is_final" BEFORE UPDATE ON "public"."analysis_attempt" FOR EACH ROW WHEN (("old"."status" = ANY (ARRAY['succeeded'::"public"."analysis_attempt_status", 'failed'::"public"."analysis_attempt_status", 'canceled'::"public"."analysis_attempt_status"]))) EXECUTE FUNCTION "public"."analysis_attempt_check_terminal_is_final"();


--
-- Name: app_user app_user_set_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE OR REPLACE TRIGGER "app_user_set_updated_at" BEFORE UPDATE ON "public"."app_user" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();


--
-- Name: audit_event audit_event_is_append_only; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE OR REPLACE TRIGGER "audit_event_is_append_only" BEFORE DELETE OR UPDATE ON "public"."audit_event" FOR EACH ROW EXECUTE FUNCTION "public"."audit_event_reject_mutation"();


--
-- Name: organization organization_count_against_creator; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE OR REPLACE TRIGGER "organization_count_against_creator" AFTER INSERT ON "public"."organization" FOR EACH ROW WHEN (("new"."created_by_user_id" IS NOT NULL)) EXECUTE FUNCTION "public"."organization_count_against_creator"();


--
-- Name: organization organization_has_a_member; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE CONSTRAINT TRIGGER "organization_has_a_member" AFTER INSERT ON "public"."organization" DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION "public"."organization_check_has_member"();


--
-- Name: organization_invite organization_invite_set_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE OR REPLACE TRIGGER "organization_invite_set_updated_at" BEFORE UPDATE ON "public"."organization_invite" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();


--
-- Name: organization_member organization_member_at_least_one_admin; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE CONSTRAINT TRIGGER "organization_member_at_least_one_admin" AFTER INSERT OR DELETE OR UPDATE ON "public"."organization_member" DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION "public"."organization_member_check_admin_remains"();


--
-- Name: organization_member organization_member_set_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE OR REPLACE TRIGGER "organization_member_set_updated_at" BEFORE UPDATE ON "public"."organization_member" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();


--
-- Name: organization organization_set_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE OR REPLACE TRIGGER "organization_set_updated_at" BEFORE UPDATE ON "public"."organization" FOR EACH ROW EXECUTE FUNCTION "public"."set_updated_at"();


--
-- Name: report report_has_an_input_file; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE CONSTRAINT TRIGGER "report_has_an_input_file" AFTER INSERT ON "public"."report" DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION "public"."report_check_has_input_file"();


--
-- Name: analysis_attempt analysis_attempt_report_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."analysis_attempt"
    ADD CONSTRAINT "analysis_attempt_report_id_fkey" FOREIGN KEY ("report_id") REFERENCES "public"."report"("id") ON DELETE CASCADE;


--
-- Name: analysis_attempt analysis_attempt_requested_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."analysis_attempt"
    ADD CONSTRAINT "analysis_attempt_requested_by_user_id_fkey" FOREIGN KEY ("requested_by_user_id") REFERENCES "public"."app_user"("id") ON DELETE SET NULL;


--
-- Name: app_user app_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."app_user"
    ADD CONSTRAINT "app_user_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;


--
-- Name: input_file input_file_report_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."input_file"
    ADD CONSTRAINT "input_file_report_id_fkey" FOREIGN KEY ("report_id") REFERENCES "public"."report"("id") ON DELETE CASCADE;


--
-- Name: organization organization_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."organization"
    ADD CONSTRAINT "organization_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."app_user"("id") ON DELETE SET NULL;


--
-- Name: organization_invite organization_invite_invited_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."organization_invite"
    ADD CONSTRAINT "organization_invite_invited_by_user_id_fkey" FOREIGN KEY ("invited_by_user_id") REFERENCES "public"."app_user"("id") ON DELETE SET NULL;


--
-- Name: organization_invite organization_invite_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."organization_invite"
    ADD CONSTRAINT "organization_invite_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE CASCADE;


--
-- Name: organization_member organization_member_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."organization_member"
    ADD CONSTRAINT "organization_member_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE CASCADE;


--
-- Name: organization_member organization_member_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."organization_member"
    ADD CONSTRAINT "organization_member_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE CASCADE;


--
-- Name: rejected_upload rejected_upload_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."rejected_upload"
    ADD CONSTRAINT "rejected_upload_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."app_user"("id") ON DELETE SET NULL;


--
-- Name: rejected_upload rejected_upload_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."rejected_upload"
    ADD CONSTRAINT "rejected_upload_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE CASCADE;


--
-- Name: report report_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."report"
    ADD CONSTRAINT "report_created_by_user_id_fkey" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."app_user"("id") ON DELETE SET NULL;


--
-- Name: report report_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."report"
    ADD CONSTRAINT "report_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE CASCADE;


--
-- Name: result_file result_file_analysis_attempt_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."result_file"
    ADD CONSTRAINT "result_file_analysis_attempt_id_fkey" FOREIGN KEY ("analysis_attempt_id") REFERENCES "public"."analysis_attempt"("id") ON DELETE CASCADE;


--
-- Name: SCHEMA "public"; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";


--
-- Name: TABLE "analysis_attempt"; Type: ACL; Schema: public; Owner: postgres
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."analysis_attempt" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."analysis_attempt" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."analysis_attempt" TO "service_role";


--
-- Name: TABLE "app_user"; Type: ACL; Schema: public; Owner: postgres
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."app_user" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."app_user" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."app_user" TO "service_role";


--
-- Name: TABLE "audit_event"; Type: ACL; Schema: public; Owner: postgres
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."audit_event" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."audit_event" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."audit_event" TO "service_role";


--
-- Name: SEQUENCE "audit_event_id_seq"; Type: ACL; Schema: public; Owner: postgres
--

GRANT UPDATE ON SEQUENCE "public"."audit_event_id_seq" TO "anon";
GRANT UPDATE ON SEQUENCE "public"."audit_event_id_seq" TO "authenticated";
GRANT UPDATE ON SEQUENCE "public"."audit_event_id_seq" TO "service_role";


--
-- Name: TABLE "input_file"; Type: ACL; Schema: public; Owner: postgres
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."input_file" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."input_file" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."input_file" TO "service_role";


--
-- Name: TABLE "kysely_migration"; Type: ACL; Schema: public; Owner: postgres
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."kysely_migration" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."kysely_migration" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."kysely_migration" TO "service_role";


--
-- Name: TABLE "kysely_migration_lock"; Type: ACL; Schema: public; Owner: postgres
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."kysely_migration_lock" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."kysely_migration_lock" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."kysely_migration_lock" TO "service_role";


--
-- Name: TABLE "organization"; Type: ACL; Schema: public; Owner: postgres
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."organization" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."organization" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."organization" TO "service_role";


--
-- Name: TABLE "organization_invite"; Type: ACL; Schema: public; Owner: postgres
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."organization_invite" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."organization_invite" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."organization_invite" TO "service_role";


--
-- Name: TABLE "organization_member"; Type: ACL; Schema: public; Owner: postgres
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."organization_member" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."organization_member" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."organization_member" TO "service_role";


--
-- Name: TABLE "rejected_upload"; Type: ACL; Schema: public; Owner: postgres
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."rejected_upload" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."rejected_upload" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."rejected_upload" TO "service_role";


--
-- Name: TABLE "report"; Type: ACL; Schema: public; Owner: postgres
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."report" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."report" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."report" TO "service_role";


--
-- Name: TABLE "result_file"; Type: ACL; Schema: public; Owner: postgres
--

GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."result_file" TO "anon";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."result_file" TO "authenticated";
GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLE "public"."result_file" TO "service_role";


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT UPDATE ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT UPDATE ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT UPDATE ON SEQUENCES TO "service_role";


--
-- Name: DEFAULT PRIVILEGES FOR SEQUENCES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

-- ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
-- ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
-- ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
-- ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";


--
-- Name: DEFAULT PRIVILEGES FOR FUNCTIONS; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

-- ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
-- ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
-- ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
-- ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: postgres
--

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT REFERENCES,TRIGGER,TRUNCATE,MAINTAIN ON TABLES TO "service_role";


--
-- Name: DEFAULT PRIVILEGES FOR TABLES; Type: DEFAULT ACL; Schema: public; Owner: supabase_admin
--

-- ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
-- ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
-- ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
-- ALTER DEFAULT PRIVILEGES FOR ROLE "supabase_admin" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";


--
-- PostgreSQL database dump complete
--


