/** Write `schema.sql`: the current shape of the `public` schema, constraints and all.
 *
 * Migrations are history, and `src/generated/` carries shape but no constraints. This is the
 * file that answers "what does this table look like right now" without reading either.
 *
 * Run through `pnpm db:gen-types`. `TEST_DB=1` selects the test stack, as everywhere.
 */

import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = fileURLToPath(new URL('../../..', import.meta.url));

// `--keep-comments` also keeps two `-- \restrict <token>` lines whose token is random per
// run. Strip just those so the output stays byte-stable for CI to diff.
const dump = execFileSync(
  `${REPO_ROOT}/scripts/supabase`,
  ['db', 'dump', '--local', '--keep-comments', '--schema', 'public'],
  { encoding: 'utf8' },
);
const lines = dump.split('\n').filter((line) => !/^-- \\(un)?restrict /.test(line));

writeFileSync(
  `${REPO_ROOT}/packages/db/schema.sql`,
  ['-- Generated by `pnpm db:gen-types`. Do not edit.', ...lines].join('\n'),
);
