/** Write `auth-schema.sql`: the `auth` schema GoTrue creates, self-contained enough to restore
 * into a fresh database created from `template0`.
 *
 * Modelled on `dump-public-schema.ts`. Unlike that file, this one's contents are decided entirely by the
 * GoTrue version the pinned Supabase CLI ships — see the `::notice::` in the `ts-db-types` CI job
 * for what to do when it drifts.
 *
 * Run through `pnpm db:gen-types`. `TEST_DB=1` selects the test stack, as everywhere.
 */

import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = fileURLToPath(new URL('../../..', import.meta.url));

// `--keep-comments` also keeps two `-- \restrict <token>` lines whose token is random per
// run. Strip just those so the output stays byte-stable for CI to diff.
const dump = execFileSync(
  `${REPO_ROOT}/scripts/supabase`,
  ['db', 'dump', '--local', '--keep-comments', '--schema', 'auth'],
  { encoding: 'utf8' },
);
const lines = dump.split('\n').filter((line) => !/^-- \\(un)?restrict /.test(line));

// `pg_dump --schema auth` groups a trigger with the table it's defined on, not with the schema
// that owns the function it calls — so it also picks up `on_auth_user_created`, which is ours,
// not GoTrue's: `001_initial_schema.ts` attaches it to `auth.users` to mirror new signups into
// `public.app_user`. Restoring it here would call a function that doesn't exist yet, since
// migrations run after this file does; stripping it leaves migration 001 to create the identical
// trigger once its function exists.
const withoutAppOwnedTriggers = lines
  .join('\n')
  .replace(
    /--\n-- Name: [^\n]*; Type: TRIGGER;[^\n]*\n--\n\nCREATE (?:OR REPLACE )?TRIGGER "[^"]+" [^\n]*EXECUTE FUNCTION "public"\.[^\n]*\n\n/g,
    '',
  );

writeFileSync(
  `${REPO_ROOT}/packages/db/auth-schema.sql`,
  `-- Generated by \`pnpm db:gen-types\`. Do not edit.\n${withoutAppOwnedTriggers}`,
);
